experiment_hash: '8a70c9296c135c4d37798249d72d2911'
base_dir: '/mnt/data/experiment_data/peeps'
orig_data_name: 'joco_original'
demo_table: 'hemank_bias_alternatives.currmatch_entity_demos'
demo_col: 'race_2way'
demo_permutations: ['White', 'NonWhite']
label: 'booking_view_warr_bw_1y'

sampling_config:
  ratio_protected: 2
  label_dis_within_protected: 'original'
  label_dis_within_non_protected: 'original'
  mode: 'under'