experiment_hash: '10ec0614881ab8f1d97754c863e39fd3'
model_group_id: 853
multiplier: 10000000
base_dir: '/mnt/data/experiment_data/donors'
orig_data_name: 'donors_original'
demo_table: 'hemank_bias_original.entity_demos3'
orig_demo_col: 'prstat_entity_id_1d_poverty_highest poverty_max'
demo_col: 'plevel'
demo_permutations: ['highest', 'not_highest']
label: 'outcome'

sampling_config:
  ratio_protected: 1
  label_dis_within_protected: 'original'
  label_dis_within_non_protected: 'original'
  mode: 'under'
