experiment_hashes: ['a1316f404aecc9df9e3c5264b32770f8']

model_group_id: 100
multiplier: 10000000

base_dir: '/mnt/data/experiment_data/elsal_new'
orig_data_name: 'original'
demo_table: 'bias_analysis_1year.entity_demos'
orig_demo_col: ''
demo_col: 'ovg'
demo_permutations: ['0', '1']
label: 'dropout'

sampling_config:
  ratio_protected: 1
  label_dis_within_protected: 'original'
  label_dis_within_non_protected: 'original'
  mode: 'under'