# Connecting to the database requires a configuration file like this one
#
# # address.of.database.server
host: el-salvador-mined.cjtbxnsr2fzp.us-west-2.rds.amazonaws.com
user: postgres
db: el_salvador_mined
# # user password
pass: treeposterbagivylabel
# # connection port
port: 5432
