experiment_hash: '53918b13ea1115d6b5d2b5b16ef4e2f4'
file_path: '/mnt/data/experiment_data/peeps/joco_original/matrices'
out_file_path: '/mnt/data/experiment_data/peeps/joco_zafar_original'
race_query: 'select entity_id, race from hemank_bias_alternatives.currmatch_entity_demos'
label_col: 'booking_view_warr_bw_1y'
demo_col: 'race'
model_group_id: 55
sa_column: 'race'
anchor_sa_value: 'W'
dest_table: 'zafar_predictions'
dest_schema: 'test_results'
train_config:
  max_iters: 300
  max_iters_dccp: 150
  tau: 0.005
  mu: 1.2
  random_seed: 112233
  EPS: 1e-4
